pipeline {
    agent any
    stages {
        stage('Code Checkout') {
            steps{
                checkout scm
            }
        }
        stage('Build And Convert to Docker Images') {
            options {
                // Timeout counter starts BEFORE agent is allocated
                timeout(time: 1, unit: 'SECONDS')
            }
            stages {
               
                stage("gateway-server build"){
                    // when { changeset "gateway-server/**" }
                    steps {
                        sh 'hostname'
                        sh 'cd gateway-server && mvn clean spring-boot:build-image -DskipTests'
                    }
                }
            }
        }
    }
}