CREATE DATABASE IF NOT EXISTS `config_server_db`;

USE config_server_db;
CREATE TABLE PROPERTIES (
  ID INT NOT NULL AUTO_INCREMENT, 
  APPLICATION TEXT, 
  PROFILE TEXT, 
  LABEL TEXT, 
  PROP_KEY TEXT,
  VALUE TEXT,
  PRIMARY KEY (ID)
 );
 GRANT ALL ON *.* TO 'user'@'%';

 select * from PROPERTIES;
 
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','default','latest','MYSQL_HOST','localhost');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','default','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','default','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','default','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','default','latest','MYSQL_DB','user_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','MYSQL_HOST','localhost');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','MYSQL_DB','product_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','default','latest','USER_SERVICE_URL','localhost:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','MYSQL_HOST','localhost');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','MYSQL_DB','inventory_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','default','latest','PRODUCT_SERVICE_URL','localhost:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','MONGO_HOST','localhost');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','MONGO_PORT','27017');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','MONGO_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','MONGO_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','MONGO_DB','cart_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','USER_SERVICE_URL','localhost:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','PRODUCT_SERVICE_URL','localhost:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','default','latest','INVENTORY_SERVICE_URL','localhost:8083');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_HOST','localhost');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','MONGO_PORT','27017');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','MONGO_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','MONGO_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','MONGO_DB','order_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','USER_SERVICE_URL','localhost:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','PRODUCT_SERVICE_URL','localhost:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','INVENTORY_SERVICE_URL','localhost:8083');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','default','latest','CART_SERVICE_URL','localhost:8084');
 
 
 
 

 
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','dev','latest','MYSQL_HOST','mysqldb');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','dev','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','dev','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','dev','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('userservice','dev','latest','MYSQL_DB','user_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','MYSQL_HOST','mysqldb');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','MYSQL_DB','product_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('productservice','dev','latest','USER_SERVICE_URL','userservice:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','MYSQL_HOST','mysqldb');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','MYSQL_PORT','3306');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','MYSQL_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','MYSQL_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','MYSQL_DB','inventory_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('inventoryservice','dev','latest','PRODUCT_SERVICE_URL','productservice:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','MONGO_HOST','mongodb');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','MONGO_PORT','27017');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','MONGO_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','MONGO_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','MONGO_DB','cart_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','USER_SERVICE_URL','userservice:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','PRODUCT_SERVICE_URL','productservice:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('cartservice','dev','latest','INVENTORY_SERVICE_URL','inventoryservice:8083');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_HOST','mongodb');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_PORT','27017');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_USER','user');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_PASSWORD','password');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','MONGO_DB','order_service_db');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','USER_SERVICE_URL','userservice:8081');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','PRODUCT_SERVICE_URL','productservice:8082');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','INVENTORY_SERVICE_URL','inventoryservice:8083');
 INSERT INTO PROPERTIES ( APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE) VALUES ('orderservice','dev','latest','CART_SERVICE_URL','cartservice:8084');

-- delete from PROPERTIES where id=58;
