apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice-deployment
  namespace: seeker-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
    spec:
      containers:
      - name: configservice
        image: ghcr.io/adminseeker/config-service:59
        
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
          limits:
            memory: "4096Mi"
            cpu: "900m"
        ports:
        - containerPort: 9000
        env:
        - name: CONFIG_MYSQL_HOST
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_MYSQL_HOST
        - name: CONFIG_MYSQL_PORT
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_MYSQL_PORT
        - name: CONFIG_MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_MYSQL_USER
        - name: CONFIG_MYSQL_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_MYSQL_PASSWORD
        - name: CONFIG_MYSQL_DB
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_MYSQL_DB
        - name: CONFIG_SERVER_USER
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_SERVER_USER
        - name: CONFIG_SERVER_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_SERVER_PASSWORD
        - name: EUREKA_URL
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: EUREKA_URL
      imagePullSecrets:
      - name: dockerconfigjson-github-com
        
---

apiVersion: v1
kind: Service
metadata:
  name: configservice-service
  namespace: seeker-store
spec:
  selector:
    app: configservice
  
  ports:
  - port: 9000
    targetPort: 9000
