apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  namespace: seeker-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: ghcr.io/adminseeker/eureka-server:53
        
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
          limits:
            memory: "4096Mi"
            cpu: "900m"
        ports:
        - containerPort: 9001
        env:
        - name: CONFIG_SERVER
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_SERVER
        - name: EUREKA_URL
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: EUREKA_URL
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      dnsConfig:
        nameservers:
        - 192.168.3.250
        searches:
        - aravindweb.com
        options:
        - name: ndots
          value: "3"
        
---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
  namespace: seeker-store
spec:
  selector:
    app: eurekaserver
  
  ports:
  - port: 9001
    targetPort: 9001
