apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
  namespace: seeker-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: ghcr.io/adminseeker/order-service:69
        
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
          limits:
            memory: "4096Mi"
            cpu: "900m"
        ports:
        - containerPort: 8085
        env:
        - name: CONFIG_PROFILE
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_PROFILE
        - name: CONFIG_LABEL
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_LABEL
        - name: RABBITMQ_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_HOSTNAME
        - name: RABBITMQ_PORT
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_PORT
        - name: RABBITMQ_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_EXCHANGE
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_EXCHANGE
        - name: RABBITMQ_ROUTING_PATTERN
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_ROUTING_PATTERN
        - name: RABBITMQ_DELIVERY_MODE
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_DELIVERY_MODE
        - name: ZIPKIN_URL
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: ZIPKIN_URL
        - name: RABBITMQ_ZIPKIN_QUEUE
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: RABBITMQ_ZIPKIN_QUEUE
        - name: EUREKA_URL
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: EUREKA_URL
        - name: CONFIG_SERVER
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: CONFIG_SERVER
        - name: VERSION
          valueFrom: 
            configMapKeyRef:
              name: seeker-store-configmap
              key: ORDERSERVICE_VERSION
      imagePullSecrets:
      - name: dockerconfigjson-github-com
        
---

apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
  namespace: seeker-store
spec:
  selector:
    app: orderservice
  
  ports:
  - port: 8085
    targetPort: 8085
