apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
          limits:
            memory: "2048Mi"
            cpu: "900m"
        ports:
          - containerPort: 5672
            name: default
          - containerPort: 15672
            name: management
        env:
          - name: RABBITMQ_NODENAME
            valueFrom: 
              configMapKeyRef:
                name: seeker-store-configmap
                key: RABBITMQ_NODENAME
        volumeMounts:
        - name: rabbitmq-data-volume
          mountPath: /var/lib/rabbitmq
          subPath: rabbitmq
      volumes:
      - name: rabbitmq-data-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
        

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - port: 5672
    targetPort: 5672
    name: default
  - port: 15672
    targetPort: 15672
    name: management
