CREATE DATABASE IF NOT EXISTS `user_service_db`;
CREATE DATABASE IF NOT EXISTS `product_service_db`;
CREATE DATABASE IF NOT EXISTS `inventory_service_db`;
CREATE DATABASE IF NOT EXISTS `config_server_db`;
GRANT ALL ON *.* TO 'user'@'%';

USE config_server_db;
CREATE TABLE PROPERTIES (
  ID INT NOT NULL AUTO_INCREMENT, 
  APPLICATION TEXT, 
  PROFILE TEXT, 
  LABEL TEXT, 
  PROP_KEY TEXT, 
  VALUE TEXT,
  PRIMARY KEY (ID)
 );

