global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['configserver:9000']

  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['eurekaserver:9001']

  - job_name: 'authservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['authservice:8090']

  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['userservice:8081']

  - job_name: 'productservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['productservice:8082']

  - job_name: 'inventoryservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['inventoryservice:8083']
  
  - job_name: 'cartservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['cartservice:8084']

  - job_name: 'orderservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['orderservice:8085']

  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['gatewayserver:9002']